name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/gradle.yml
  pull_request:
    branches: [ "master" ]
    paths:
      - .github/workflows/gradle.yml
  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload Jar Artifact
      uses: actions/upload-artifact@v4
      with:
        name: worldRewards
        path: build/libs/*.jar
